CREATE DATABASE EXERCICIOS_AULA;

EXERCICIO 1 : 

CREATE TABLE IF NOT EXISTS FORNECEDOR (
    FCODIGO INT PRIMARY KEY,
    FNOME VARCHAR(255) NOT NULL,
    STATUS BOOLEAN DEFAULT 'TRUE',
    CIDADE VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PECA(
    PCODIGO INT PRIMARY KEY,
    PNOME VARCHAR(255) NOT NULL,
    COR VARCHAR(50) NOT NULL,
    PESO DECIMAL (10, 2) NOT NULL,
    CIDADE VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS INSTITUICAO(
    ICODIGO INT PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS PROJETO(
    PRCOD INT PRIMARY KEY,
    PRNOME VARCHAR(255),
    CIDADE VARCHAR(255),
    ICODIGO INT NOT NULL,
    FOREIGN KEY (ICODIGO) REFERENCES INSTITUICAO(ICODIGO)
);

CREATE TABLE IF NOT EXISTS FORNECIMENTO (
    FCODIGO INT PRIMARY KEY,
    PCODIGO INT,
    PRCOD INT,
    FOREIGN KEY (FCODIGO) REFERENCES FORNECEDOR (FCODIGO),
    FOREIGN KEY (PCODIGO) REFERENCES PECA (PCODIGO),
    FOREIGN KEY (PRCOD) REFERENCES PROJETO (PRCOD),
    QUANTIDADE INT
);

************************************************************************************

EXERCICIO 2 :

CREATE TABLE CIDADE(
    CCOD INT PRIMARY KEY, 
    CNOME VARCHAR(50) NOT NULL,
    UF VARCHAR(10) NOT NULL
);

----------------------------------------------------------------
ALTER TABLE FORNECEDOR
ADD COLUMN FONE VARCHAR(20),
ADD COLUMN CCOD INT NOT NULL;

ALTER TABLE FORNECEDOR
ADD FOREIGN KEY (CCOD) REFERENCES CIDADE;

ALTER TABLE FORNECEDOR
DROP COLUMN CIDADE;
----------------------------------------------------------------
ALTER TABLE CIDADE